### ISSUE TITLE
UPF does not forward returned packets to the gnb

### ISSUE THREAD

**Issue by gibson3659** [Gradiant/openverso-charts#28] opened 2021-11-02 22:31 UTC
Hi.  I deployed these charts on aws eks, and everything seems to work fine except the NAT.  I see the packets go out the upf to the internet but the responses don't make it back to the gnb or ue.  Any ideas?

**Comment by cgiraldo** [comment] 2021-11-03 10:15
We have only test the helm charts in kubernetes baremetal. 
So I can't help you here. Maybe there is something to configure in aws security-groups?

I can share some info on how upf works. open5gs image [entrypoint.sh](https://github.com/kleveross/ormb) creates a tun interface if the command is `open5gs-upfd`. Container runs in privileged mode for that. Also if `ENABLE_NAT` environment variable is true (image default value), the entrypoint configures iptables NAT rule:

```
iptables -t nat -A POSTROUTING -s $IPV4_TUN_SUBNET ! -o ogstun -j MASQUERADE;
```

with the default value IPV4_TUN_SUBNET="10.45.0.0/16"
 
Please, if you get it to work, share your solution.

**Comment by DiogoCruz40** [comment] 2022-02-20 19:58
The problem is not in the NAT is in the route, you can send packages to the internet, but when they return they don´t know where the tunnel is, you have to route it to there, i m still trying to find a solution

**Comment by avrodriguezgrad** [comment] 2022-03-04 09:19
we are going to close the issue, if you want to open it again because you still have the problem, do it!
Regards

**Closed by avrodriguezgrad** 2022-03-04 09:19 UTC
