### ISSUE TITLE
TLS on SBI Interfaces

### ISSUE THREAD

**Issue by LuisLoureiro2000** [Gradiant/openverso-charts#131] opened 2023-07-06 22:57 UTC
Hi!

I am trying to configure and enable TLS in SBI interfaces. I used your project to deploy Open5GS inside a kubernetes cluster.  I started by changing the config files, setting the "no_tls" value to "false". 

After that i used openssl to generate the CA and create certificates to the NFs (i only created for the AUSF for now). Then i tried to move the ca.crt, ausf.key and ausf.crt to the pod container of the AUSF with the command: 

kubectl cp file-spec-src file-spec-dest -c specific-container

However, i was getting erros due to permissions, and even when i tried to move to the /tmp directory, everytime i restarted the pod, the files just got deleted so it was not a solution. So i tried this, with "no_tls" as "true", so it can create the pod AND to create the certificates in the /tmp/tls directory:

![image](https://github.com/open5gs/open5gs/assets/72310398/fd26fe96-9474-4082-8369-d44ed066db29)

and then run this command

helm upgrade --install -f open5gs.yaml open5gs openverso/open5gs -n open5gs , 

And then run it again, but with value of "false" 

![image](https://github.com/open5gs/open5gs/assets/72310398/d938c648-40a8-4f2d-bee0-0f8a7de06c7a)

and then run this command again

helm upgrade --install -f open5gs.yaml open5gs openverso/open5gs -n open5gs

Now when i go into the /tmp/tls directory i see the certificates. (I checked with cat and the certificates seem all okay):

![image](https://github.com/open5gs/open5gs/assets/72310398/2429eb24-3676-4cdc-bba7-0efc856b558a)

and when i look into the ausf.yaml file it looks like this

![image](https://github.com/open5gs/open5gs/assets/72310398/41c660a2-f41d-4e8b-a4e3-494281cb13c8)

However, isn't the ausf.yaml file supposed to have the path of certificates? 
![image](https://github.com/open5gs/open5gs/assets/72310398/feb98d3b-5dfb-4a26-8041-f97f198b5b4c)

Also, how can i check if tls is actually working with curl? When i executed curl commands with https i get an error:

![image](https://github.com/open5gs/open5gs/assets/72310398/7eb9bb87-3ea2-47aa-b2fb-37d198e64e56)

Can someone help me on this please?

Regards,
Luís Loureiro

**Comment by cgiraldo** [comment] 2023-07-07 05:51
Hi Luis,

We do not actually support setting cacert, key and cert in the helm chart values (check https://github.com/Gradiant/openverso-charts/blob/master/charts/open5gs-ausf/values.yaml).

You can try to provide the full ausf configuration in the "customOpen5gsConfig" helm chart value key. 

Another option is, on runtime, to edit the corresponding open5gs-ausf configmap to add the 'cacert' 'key' and 'cert' and restart the pod.

To check with curl you have to add the flag `--http2-prior-knowledge`.

**Comment by avrodriguezgrad** [comment] 2023-07-10 08:35
Hi Luis,

As Carlos said, we don't provide support for TLS, so, we don't have expertise resolving these kind of issues.

Nevertheless, I think you can comment your issue in the open5gs repo, as I believe this problem is more related with the framework rather than the chart.

Best regards,

**Comment by LuisLoureiro2000** [comment] 2023-07-10 13:55
Ok, i was finally able to do it. 

![image](https://github.com/Gradiant/openverso-charts/assets/72310398/83eb85b7-f177-4a35-b2a2-6f599bbda29c)

But for some reason, even after restarting all pods, the AMF and SMF are always crashing. There is also this error in every nf. Do you know what it is?

![image](https://github.com/Gradiant/openverso-charts/assets/72310398/7a9eb1c4-7768-4534-8d42-3a1b25ac04e5)

**Comment by avrodriguezgrad** [comment] 2023-07-11 10:40
Sorry Luis, but I don't know what is the cause of your problem. I think you can put your issue in the open5gs repo and try to get better help for this.

BR,
Álvaro

**Closed by avrodriguezgrad** 2023-07-11 10:40 UTC
